name: BattlePass
version: 3.1
main: io.github.battlepass.BattlePlugin
api-version: 1.13
soft-depend:
  - AdvancedEnchantments
  - ASkyBlock
  - AuctionHouse
  - Bedwars1058
  - BuildBattle
  - ChatReaction
  - ChestShop
  - Clans
  - CrateReloaded
  - CratesPlus
  - CrazyCrates
  - CrazyEnvoy
  - DiscordMinecraft
  - Factions
  - Jobs
  - KoTH
  - Lands
  - PlaceholderAPI
  - MoneyHunters
  - PlotSquared
  - ProCosmetics
  - StrikePractice
  - SuperiorSkyblock2
  - TokenEnchant
  - USkyBlock
  - Votifier
  - LuxuryQuests

commands:
  battlepass:
    aliases: [bp, battlep, bpass]
  battlepassadmin:
    aliases: [bpa, battlepassa, bpadmin]

permissions:
  battlepass.admin:
    description: none
  battlepass.premium:
    description: none